# Generated by Django 4.0 on 2022-11-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='opportunity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
