# Generated by Django 4.0 on 2022-09-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('day_rate', models.FloatField()),
                ('cf_number', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('item_image', models.CharField(default='https://eu.evocdn.io/dealer/1065/catalog/product/images/cs_1612369426.png', max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.CharField(max_length=500)),
                ('risk_impact', models.IntegerField()),
                ('risk_probability', models.IntegerField()),
                ('risk_mitigation', models.CharField(max_length=500)),
                ('risk_owner', models.CharField(max_length=200)),
                ('risk_status', models.CharField(max_length=500)),
                ('date_opened', models.DateField()),
            ],
        ),
    ]
