# Generated by Django 4.0 on 2022-09-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('Data Architect', 'Data Architect'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Solution Architect', 'Solution Architect'), ('Business Analyst', 'Business Analyst'), ('Project Manager', 'Project Manager'), ('Project Coordinator', 'Project Coordinator'), ('Subject Matter Expert', 'Subject Matter Expert'), ('Product Owner', 'Product Owner'), ('Safety Engineer', 'Safety Engineer'), ('Team Lead', 'Team Lead'), ('UX Designer', 'UX Designer'), ('Project Lead', 'Project Lead')], max_length=200)),
                ('day_rate', models.FloatField()),
                ('cf_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('impact', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('probability', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('mitigation', models.CharField(max_length=500)),
                ('owner', models.CharField(choices=[('Romi Dhillon', 'Romi Dhillon'), ('Serena Haak', 'Serena Haak'), ('Tom Kinnear', 'Tom Kinnear'), ('Joe Collis', 'Joe Collis')], max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=500)),
                ('date_opened', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ii_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ii_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ii_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ii_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending_date', models.DateField()),
                ('hours', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ii_app.project')),
            ],
        ),
    ]
