# Generated by Django 4.0 on 2022-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ii_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='cf_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_position',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_cost',
        ),
        migrations.AddField(
            model_name='employee',
            name='day_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='project_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
