# Generated by Django 4.0 on 2023-02-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ii_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cv',
            field=models.FilePathField(),
        ),
    ]
