# Generated by Django 4.0 on 2023-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ii_app', '0002_alter_resource_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cv',
            field=models.FileField(upload_to='media'),
        ),
    ]
