# Generated by Django 4.0 on 2022-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ii_app', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(default='https://eu.evocdn.io/dealer/1065/catalog/product/images/cs_1612369426.png', max_length=500),
        ),
    ]
