# Generated by Django 4.0 on 2022-09-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ii_app', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='image',
            new_name='item_image',
        ),
    ]
