# Generated by Django 4.0 on 2022-09-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ii_app', '0006_rename_image_employee_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.CharField(max_length=500)),
                ('risk_impact', models.IntegerField()),
                ('risk_probability', models.IntegerField()),
                ('risk_mitigation', models.CharField(max_length=500)),
                ('risk_owner', models.CharField(max_length=200)),
                ('risk_status', models.CharField(max_length=500)),
                ('date_opened', models.DateField(max_length=50)),
            ],
        ),
    ]
